name: intl_date_helper
description: "A simple utility for date formatting, conversion, and timezone support."
version: 0.1.0
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15
